export const PAYMENT_TYPES = [
  'Donation',
  'Event',
  'Campaign',
  'Religious Articles',
  'Hebrew School',
  'Bar/Bat Mitzvah',
  'Adult Education/Event',
  'Holiday',
  'Income',
  'Gan Montessori',
  'Youth',
  'Facility Rental',
  'Wedding',
];

export const PAYMENT_SUBTYPES = [
  'General',
  'High Holidays',
  'Fundraiser',
  'Partnership',
  'Shul',
  'Holidays',
  'Auction',
  'Wishlist',
  'Scholarship',
  'Lecture',
  'Building Fund',
  'Shabbat Dinner',
  'Program Sponsorship',
  'Yizkor',
  'Sale of Chametz',
  'Charitable Causes',
  'Funeral',
  'In Memory Of',
  'Gala Appeal',
  'Gan Montessori',
  'Security',
  'Membership',
  'Rabbi',
  'Gan Scholarship',
  'Wedding',
];

export const RECURRING_FREQUENCIES = [
  'Monthly',
  'Quarterly',
  'Yearly',
];
